name: pyfecons
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=24.0
  - cadquery=2.4.0
  - pip:
    - contourpy==1.2.0
    - cycler==0.12.1
    - ezdxf==1.2.0
    - fonttools==4.49.0
    - kiwisolver==1.4.5
    - matplotlib==3.8.3
    - multimethod==1.9.1
    - nlopt==2.7.1
    - nptyping==2.0.1
    - numpy==1.26.4
    - ordered-set==4.1.0
    - packaging==23.2
    - pandas==2.2.1
    - path==16.10.0
    - pillow==10.2.0
    - pyparsing==3.1.1
    - python-dateutil==2.9.0.post0
    - requests==2.31.0
    - scikit-learn==1.4.0
    - scipy==1.12.0
    - six==1.16.0
    - typing_extensions==4.10.0
    - typish==1.9.3
