name: pyfecons
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=24.0
  - pip:
    - matplotlib==3.9.0
    - numpy==2.0.0
    - pandas==2.2.2
    - requests==2.32.3
    - scikit-learn==1.5.0
    - scipy==1.13.1
