from dataclasses import dataclass

from pyfecons.enums import MagnetType, MagnetMaterialType
from pyfecons.units import Meters, Ratio


@dataclass
class Magnet:
    name: str
    type: MagnetType
    material_type: MagnetMaterialType
    coil_count: int
    r_centre: Meters  # radius of each coil
    z_centre: Meters  # vertical coordinates of centre of each coil (r=0)
    dr: Meters  # total coil thickness in r direction (radial)
    dz: Meters  # total coil thickness in z direction (vertical)
    # Total fraction of cross-sectional area comprised of insulation
    # (for copper or tape-tape pancake geometry)
    frac_in: Ratio
    coil_temp: float  # TODO what are the units, C or K?
    mfr_factor: float  # Manufacturing factor for each coil
    # For each magnet
    # if using HTS CICC, True to autogen paramters from field and radius
    # False to use input parameters
    auto_cicc: bool = False
    # auto_cicc fields only used if auto_cicc is True
    auto_cicc_b: float = None  # central field of each autogenerated HTS CICC coil
    auto_cicc_r: Meters = None  # radius of each autogenerated HTS CICC coil
